# ELIMINAR esta línea:
# version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27030:27030"

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}  # Usará la variable de entorno de Coolify
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
    restart: always

volumes:
  mongo_data: