version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/miproject?authSource=admin
    ports:
      - "8443:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: always
volumes:
  mongo_data: